<form method="get" class="form-horizontal">
	<div class="modal fade" tabindex="-1" role="dialog" id="module-search">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title">
						<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
						<?php echo $this->translate('Module Search'); ?>
					</h4>
				</div>
				<div class="modal-body">
				
				
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
					<button type="submit" class="btn btn-primary"><?php echo $this->translate('Search'); ?></button>
				</div>
			</div>
		</div>
	</div>
</form>